### PR TITLE
Fix some bugs of `CircuitInputBuilder`

### LINKED ISSUE #431: testnet: Call stack is empty but call is used
Run the following command inside the zkevm-chain repo to reproduce:
`docker run --pull --rm -v $(pwd):/host -e 'RUST_BACKTRACE=1' -e 'RPC_URL=https://zkevmchaingeth1.efprivacyscaling.org/rpc/l2' -e 'BLOCK_NUM=1' -e 'PARAMS_PATH=/host/params' --entrypoint /prover_cmd ghcr.io/appliedzkp/zkevm-chain/coordinator:latest`

####### output

```sh
[2022-04-06T09:30:50Z WARN  bus_mapping::circuit_input_builder] This does not look like a EIP-1559 block - base_fee_per_gas defaults to zero
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode CODECOPY
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode LOG3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SSTORE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode DELEGATECALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode RETURNDATASIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode ADDRESS
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode EXTCODESIZE
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode STATICCALL
[2022-04-06T09:30:50Z WARN  bus_mapping::evm::opcodes] Using dummy gen_associated_ops for opcode SHA3
thread 'main' panicked at 'gen_inputs for BLOCK_NUM: InvalidGethExecTrace("Call stack is empty but call is used")', prover/src/bin/prover_cmd.rs:65:10
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/core/src/panicking.rs:106:14
   2: core::result::unwrap_failed
             at ./rustc/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/core/src/result.rs:1613:5
   3: prover_cmd::main::{{closure}}
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::thread_pool::ThreadPool::block_on
   6: tokio::runtime::Runtime::block_on
   7: prover_cmd::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by han0110**
This PR aims to fix some bugs of `CircuitInputBuilder` to resolve #431, it includes:

1. Doing `push_call` and `handle_return` for other call-family opcodes by `dummy_gen_call_ops`.
2. Add a copy of caller's memory as `call_data_source` in struct `CallContext` struct for `CALLDATACOPY` to be able to generate memory operations and remove `unimplement!`. However, it doesn't work when I tried to apply to circuit testing, need more investigation (appliedzkp/zkevm-specs#134 also needs to be addressed).
3. Add address into access set when code information (e.g. length and bytes) is accessed.
4. Since `CALLDATASIZE` has its `gen_associated_ops` implemented, I tried to replace handcrafted testing data for it in circuit testing to make sure it works (and unblock #419).

### CODE REVIEW

File: zkevm-circuits/src/evm_circuit/execution/calldatasize.rs [hunk 1]
```diff
@@ -89,108 +89,98 @@ impl<F: Field> ExecutionGadget<F> for CallDataSizeGadget<F> {
...
+                        accs[1]
+                            .address(address!("0x0000000000000000000000000000000000000010"))
+                            .balance(Word::from(1u64 << 20))
+                            .code(bytecode);
+                    },
+                    |mut txs, accs| {
+                        txs[0]
+                            .from(accs[0].address)
+                            .to(accs[1].address)
+                            .input(vec![0; call_data_size].into())
```
Comment (ed255) [inline zkevm-circuits/src/evm_circuit/execution/calldatasize.rs:122]:
```suggestion
                            .input(rand_bytes(call_data_size).into())
```
I think it's always better to use non-zero values for tests.

**Review by ed255 — APPROVED** [review]
I've left two minor suggestions.  Feel free to apply them or not!
LGTM, thanks for fixing this :)

**Review by roynalnaruto — APPROVED** [review]
I had uncommitted changes trying to do something similar in https://github.com/appliedzkp/zkevm-circuits/pull/402, but I will wait for this to be merged before, so I can wrap up the `CALLDATALOAD` internal call case :)

The changes look good to me! Just a tiny suggestion, it would be better to add a test to the `CALLDATACOPY` [opcode implementation](https://github.com/appliedzkp/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/calldatacopy.rs#L490) that uses these `bus-mapping` updates to generate witness:

```rust
#[test]
fn calldatacopy_busmapping_internal() {
    let creator_code: Vec<u8> = hex::decode("666020600060003760005260076019F3").unwrap();
    let code = bytecode! {
        // 1. Store the following bytes to memory
        PUSH16(Word::from_big_endian(&creator_code))
        PUSH1(0x00) // offset
        MSTORE

        // 2. Create a contract with code: 6020 6000 6000 37
        PUSH1(0x10) // size
        PUSH1(0x10) // offset
        PUSH1(0x00) // value
        CREATE

        // 3. Call created contract, i.e. CALLDATACOPY (37) is in internal call
        PUSH1(0x00)   // retSize
        PUSH1(0x00)   // retOffset
        PUSH1(0x20)   // argsSize
        PUSH1(0x00)   // argsOffset
        PUSH1(0x00)   // value
        DUP6          // address
        PUSH2(0xFFFF) // gas
        CALL
    };

    // TODO: build and handle block
    // TODO: assertions on the CALLDATACOPY step
}
```

File: bus-mapping/src/circuit_input_builder.rs [hunk 2]
```diff
@@ -888,11 +891,25 @@ impl<'a> CircuitInputStateRef<'a> {
 
     /// Push a new [`Call`] into the [`Transaction`], and add its index and
     /// [`CallContext`] in the `call_stack` of the [`TransactionContext`]
-    pub fn push_call(&mut self, call: Call) {
-        let call_id = call.call_id;
+    pub fn push_call(&mut self, call: Call, step: &GethExecStep) {
+        let call_data_source = match call.kind {
```
[the remark this answers is not in the document]
Comment (han0110) [reply bus-mapping/src/circuit_input_builder.rs:895]: I thought about that, but while generating the memory read, the `memory_address` has not offset, so I think it's more straightforward to just have the complete caller memory, to avoid carrying the `call_data_offset` and adding it for every read.

**Comment by han0110** [comment]
> it would be better to add a test to the CALLDATACOPY [opcode implementation](https://github.com/appliedzkp/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/calldatacopy.rs#L490) that uses these bus-mapping updates to generate witness:

@roynalnaruto Thanks for the code snippet, I tried that once but failed, then I realized appliedzkp/zkevm-specs#134 has not been addressed yet, so I think it would be better to fix that in spec and then circuit.

File: bus-mapping/src/circuit_input_builder.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (ed255) [reply bus-mapping/src/circuit_input_builder.rs:902]: I see, thanks for the explanation!  Sounds good then to use `call_data_source`

File: bus-mapping/src/circuit_input_builder.rs [hunk 3]
```diff
@@ -439,6 +439,8 @@ pub struct CallContext {
     /// call. It is incremented when a subcall in this call succeeds by the
     /// number of successful writes in the subcall.
     pub reversible_write_counter: usize,
+    /// Call data source (copy of caller's memory or tx input)
+    pub call_data_source: Vec<u8>,
```
Comment (icemelon) [inline bus-mapping/src/circuit_input_builder.rs:443]: Just call it `call_data`?

```suggestion
    pub call_data: Vec<u8>,
```

**Review by icemelon — APPROVED** [review]
overall LGTM!

File: bus-mapping/src/circuit_input_builder.rs (hunk 3 above)
Comment (han0110) [reply bus-mapping/src/circuit_input_builder.rs:443]: But it's not really the `call_data` we used to know, it's complete memory of caller instead of sliced. I was afraid it would be confusing so made it `call_dada_source` (then we can index the byte by absolute address instead of relative one). Not sure if it makes sense, I can also update this to the real `call_data`. What do you think?

Comment (icemelon) [reply bus-mapping/src/circuit_input_builder.rs:443]: ah, I see. I thought it was just the real `call_data`. The reason you take a snapshot of the entire caller memory is that you want to use `calldata_offset + index` to read the caller memory in the `CALLDATALOAD`, right? I think it'd be fine

Comment (han0110) [reply bus-mapping/src/circuit_input_builder.rs]: Yeah, but I just think it's really confusing, so I made a change to have `call_data` instead of `call_data_source` in [`4d0ee80`](https://github.com/appliedzkp/zkevm-circuits/pull/434/commits/4d0ee80c3059effb56043b97071b72a8c5785fc1)

**Comment by roynalnaruto** [comment]
@han0110 The above bytecode fails via bus-mapping because `CREATE` does not push a `call`, but `RETURN` (soon following the `CREATE` opcode) pops the `call_ctx` while `state.handle_return()`.

So we then end up with this error:
```
panicked at 'called `Result::unwrap()` on an `Err` value: InvalidGethExecTrace("Call stack is empty but call is used")'
```

**Comment by han0110** [comment]
Ah, I didn't expect `CREATE` to be used so soon :(   Let me try to implement a `dummy_gen_create_ops` in `CircuitInputBuilder`.

To unblock #450 first, could we just set the code of callee directly instead of deploy the callee?
