### PR TITLE
Read caller's `CalleeAddress` instead of `CallerAddress` for new context's caller

### LINKED ISSUE #602: Read-write inconsistency in CallDataLoad and CallDataCopy
My understanding of read-write consistency is that non-first access reads should not change row.value, but the following tests fail when I make the changes in this PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/601:

---- evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_multi_step stdout ----
thread 'evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_multi_step' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_simple stdout ----
thread 'evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_simple' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29

---- evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_out_of_bound stdout ----
thread 'evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_out_of_bound' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29

---- evm_circuit::execution::calldataload::test::calldataload_gadget_internal stdout ----
thread 'evm_circuit::execution::calldataload::test::calldataload_gadget_internal' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29

---- evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_zero_length stdout ----
thread 'evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_zero_length' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29

@ed255  and @han0110, is something wrong with my understanding of what rw consistency is, or is there a bug in the bus mapping for the calldata gadgets?

### PR DESCRIPTION
**Pull request by han0110**
This PR fixes the inconsistency with spec in `CALL`.

Resolves #602.

### CODE REVIEW

File: zkevm-circuits/src/evm_circuit/execution/call.rs [hunk 1]
```diff
@@ -91,7 +91,7 @@ impl<F: Field> ExecutionGadget<F> for CallGadget<F> {
         let tx_id = cb.call_context(None, CallContextFieldTag::TxId);
         let mut reversion_info = cb.reversion_info(None);
         let [caller_address, is_static, depth] = [
```
Comment (z2trillion) [inline zkevm-circuits/src/evm_circuit/execution/call.rs:93]: Do you need to update the name of this variable as well, or is it the case that the caller_address in this context is the callee_address of the previous context?

Comment (han0110) [reply zkevm-circuits/src/evm_circuit/execution/call.rs:93]: > is it the case that the caller_address in this context is the callee_address of the previous context?

Yes.

Perhaps we should use `current_address` here.

**Review by z2trillion — APPROVED** [review]
looks good!
